### ISSUE TITLE
About the Training Environment

### ISSUE THREAD

**Issue by dkerjw1** [AugmentariumLab/omnisyn#1]
It's a really amazing work, and I want to train on the dataset, but I have a question about the environment.
I noticed that this work depend on habitat library and pytorch3d library both, but habitat only compatible with python2 and pytorch only compatible with python3. So If you can give me more details about the training environment?
Thanks a lot.

**Comment by EchoTHChen** [comment]
@qingyuemeng I also met this problem. How did you resolve this problem?

**Comment by dli7319** [comment]
Please see the install instructions for [facebookresearch/habitat-lab](https://github.com/facebookresearch/habitat-lab) which supports python3. This is only used for generating matterport data.

**Comment by EchoTHChen** [comment]
> Please see the install instructions for [facebookresearch/habitat-lab](https://github.com/facebookresearch/habitat-lab) which supports python3. This is only used for generating matterport data.

Thanks!
