### ISSUE TITLE
Should this line be revised?

### ISSUE THREAD

**Issue by EchoTHChen** [AugmentariumLab/omnisyn#11]
https://github.com/AugmentariumLab/omnisyn/blob/601556b788f8dc6980048f1c674cf3c3b76d676b/data_readers/create_rgb_dataset.py#L132

I used this line, but it did not report errors (The `data/scene_episodes` directory has been deleted)?

**Comment by dli7319** [comment]
I think you're right.
I changed the code to use `data_readers/scene_episodes` and the next few lines to output an error if it's not found.
