### ISSUE TITLE
About the parameters in m3d_depth_config.txt

### ISSUE THREAD

**Issue by EchoTHChen** [AugmentariumLab/omnisyn#5]
The parameters `alignment-use-xyz=True` and `offset-loss-factor=5` do not appear in the options.py. If I remove them directly in the m3d_depth_config.txt, is there any negative effect to the network training? In other words, could I directly remove them?

**Comment by dli7319** [comment]
My bad. I just removed those options from the config file. When doing a little bit of cleanup I changed `parse_known_args` to `parse_args` but forgot to remove those in the config.

**Comment by EchoTHChen** [comment]
Thanks for your reply!
