### ISSUE TITLE
Similar Images for training and testing datasets

### ISSUE THREAD

**Issue by EchoTHChen** [AugmentariumLab/omnisyn#9]
When I load the training data and testing data, I find that they are the same images. Generally, they should not be the same. How can I solve this issue?

the first panorama from training data:
![train_pano_np](https://user-images.githubusercontent.com/32491440/192322913-6ff0a4cd-c3fb-4d1b-a548-5825d51cdd31.jpg)

the first panorama from testing data:
![val_pano_np](https://user-images.githubusercontent.com/32491440/192323008-dabd8cb3-194f-419d-94dc-b88160079e64.jpg)

I use the following code to load the data:
```
from torch.utils.data import DataLoader
from data_readers.habitat_data import HabitatImageGenerator
def load_train_data(full_width, full_height, m3d_dist):
    # args.dataset_name == "m3d":
    train_data = HabitatImageGenerator(
        "train",
        full_width=full_width,
        full_height=full_height,
        m3d_dist=m3d_dist
    )

    train_dataloader = DataLoader(
        dataset=train_data,
        num_workers=0,
        batch_size=1,
        shuffle=False,
        drop_last=True,
        pin_memory=True,
    )
    return train_data, train_dataloader

def load_valid_data(full_width, full_height, m3d_dist):
    # args.dataset_name == "m3d":
    val_data = HabitatImageGenerator(
          "test",
          full_width=full_width,
          full_height=full_height,
          m3d_dist=m3d_dist)
    val_dataloader = DataLoader(
        dataset=val_data,
        num_workers=0,
        batch_size=1,
        shuffle=False,
        drop_last=True,
        pin_memory=True,
    )
    return val_data, val_dataloader


# for epoch in range(args.epochs):

train_data, train_loader = load_train_data(1024, 512, 1.0)
val_data, val_loader = load_valid_data(1024, 512, 1.0)
mode='train'
if mode=="val":
    loader = val_loader
elif mode=='train':
    loader = train_loader
for i, data in enumerate(loader):
    panos = data["rgb_panos"]#.to(args.device)
    depths = data["depth_panos"]#.to(args.device)
    rots = data["rots"]#.to(args.device)
    trans = data["trans"]#.to(args.device)
    # panos.shape
    import cv2
    import numpy as np
    print(panos.shape)
    pano_np = np.uint8(panos[0, 0].data.cpu().numpy()*255)
    cv2.imwrite(mode+"_pano_np.jpg", pano_np)
    import pdb;pdb.set_trace()
```

**Comment by EchoTHChen** [comment]
Do you have any idea to solve this issue(or bug)?

**Comment by dli7319** [comment]
My bad. There was a typo in my code but `create_rgb_dataset.py` is eventually pulling positions from `data/scene_episodes/mp3d_train/dataset_one_ep_per_scene.json.gz`.  
This file should be 6kb and different from the mp3d_test file.

The correct train image using your code (RGB reversed) is 
![train_0_pano_np](https://user-images.githubusercontent.com/27523415/194953222-e3c316ed-a756-463e-ab9b-36eb4ce012b7.jpg)

It's possible that my matterport results are messed up though. I need to double-check them.

**Comment by EchoTHChen** [comment]
Sorry, I do not understand your words. I use your updated data_readers/habitat_data.py to visualize the first training image. It is still the same as the first one in testing images. Did you fix your bug?

**Comment by dli7319** [comment]
Can you check to see if you have the following files:
```
data/scene_episodes/mp3d_train/dataset_one_ep_per_scene.json.gz
data/scene_episodes/mp3d_test/dataset_one_ep_per_scene.json.gz
data/scene_episodes/mp3d_val/dataset_one_ep_per_scene.json.gz
```
These should all be different from each other. I copied them from the data_readers folder.

**Comment by EchoTHChen** [comment]
I have them and their sizes are different .

**Comment by dli7319** [comment]
Could you check if the correct files are being read from https://github.com/AugmentariumLab/omnisyn/blob/main/data_readers/create_rgb_dataset.py#L138

**Comment by EchoTHChen** [comment]
When I use the test split, it seems that the code does not run the `https://github.com/AugmentariumLab/omnisyn/blob/main/data_readers/create_rgb_dataset.py#L138`.
